### ISSUE TITLE
What is the requirement for the Primitive Cell

### ISSUE THREAD

**Issue by VIGNESHinZONE** [VlachosGroup/lcnn#2]
I had a hard time trying to understand, why neighbours for a data point are extracted using primitive cell?
 
iso.GraphMatcher() is used for finding neighbours which use the networkx graph of the active site enivronment in primitive cell and matches it with the networkx graph active site for the data point. And when I had looked upon the documentation for iso.GraphMatcher, it just finds the isomorphic graph mapping for the given inputs two input graphs.
So could you please tell me, why does the networkx graph of the primitive cell environment need to be isomorphic with the site environment of the datapoint?  

Code given in this line https://github.com/VlachosGroup/lcnn/blob/72abd5727940f55cd5e66159a4ba2c053b3198c3/lcnn/data/UniversalLoader.py#L343
  
Im looking for a more intuitive explanation rather than a purely mathematical one.

**Comment by googhgoo** [comment]
The graph for isomorphism to identify neighbor site is done using the primitive cell. In actuality, the graph does not necessarily needs to be constructed from the primitive cell.

**Comment by VIGNESHinZONE** [comment]
Please correct me if Im wrong about my assumptions, 
1) Point group analyser is only applied on primitive cell and all the different permutations with respect to the primitive cell are extracted. This is constructed only on the neighbours of the 'A1' site from the primitive cell.
2) And then isomorphic graph matcher algorithm is applied with the neighbours of 'A1' site of the data point and that of the primitive cell. And after that, those permutations of the primitive cell are applied to the site of the data point.

But my doubt revolves around step 2, why are we assuming an isomorphic relation between the 'A1' surrounding site in primitive cell and the data point neighbours??

**Comment by googhgoo** [comment]
(1) and (2) are correct.

Regarding the isomorphic relations, we were interested in solving cluster expansion problem. i.e. periodic cells in all the data points are built via lattice transformation of the primitive cell. Thus, the neighbor environment in the primitive cell is identical to the environment in the data points.

**Comment by VIGNESHinZONE** [comment]
Thank you very much, 
Is there any chance you could convert the license of the code to MIT?

**Comment by VIGNESHinZONE** [comment]
Thank You very much for the help and also for changing the license
